// <auto-generated />
namespace AMSMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateSubjectallocations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateSubjectallocations));
        
        string IMigrationMetadata.Id
        {
            get { return "201805181548578_updateSubjectallocations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
